require("./style/article.less")
require("./style/go-top.less")
require("./style/image.less")
require("./style/backlinks.less")
require("./style/sidebar.less")
require("./style/style-item.less")
require("./script/script-item.js")
require("./style/article-code.less")
require("./style/article-table.less")

//require("./style-print/gutenberg.min.less")
require("./style-print/style-print.less")